### ISSUE TITLE
Support remote shockers

### ISSUE THREAD

**Issue by redmushie** [OpenShock/ShockOsc#12]
Instead of only triggering local shockers it would be amazing to also support remote shockers via share links.

Think having a button that says "Shock everyone" ingame and on interact it would transmit to shockers of multiple people.

**Comment by LucHeart** [comment]
In theory this already works, by entering a shocker id that you have a DIRECT share to. Share links will probably not support this, since they are not meant for integrating like this.

However this is a challenge on the configuration side of things. Would probably need a UI first. Config is already a mess sofar :D

**Comment by redmushie** [comment]
Shouldn't be too bad in theory?

Theoretical:
```json
"share-id": {
  "shocker-name-here": "id-here",
  ...
}
```

Or something. You get the gist of it

**Comment by LucHeart** [comment]
as said, that already works as is right now

**Comment by LucHeart** [comment]
its more so a question about usability and configuration friendliness that comes with it. 
Dont wanna really add complicated features like this without this being done https://github.com/OpenShock/ShockOsc/issues/14

**Comment by redmushie** [comment]
I was responding to the second paragraph of your message ya bingus

**Comment by LucHeart** [comment]
You have to consider, that you might wanna group them together under a single parameter to use via osc,

**Comment by redmushie** [comment]
Yeah. My intent with #12 and #13 is to be able to make an ingame control pad that a third party can use to control the shockers of one or more other people.

**Comment by LucHeart** [comment]
Oh yeah defo

**Comment by BytewaveMLP** [comment]
Hi there! I know this is a bit of an older issue, but I wasn't sure where best to raise it.

It seems as though the proposed workaround for adding shared shockers no longer works since ShockOSC has moved to being an OpenShock module. Whenever I start the app, the list of shocker IDs in my group is typically overwritten with an empty array. And even if that doesn't happen for whatever reason, the shock message never actually seems to be delivered to OpenShock - I can see from the logs that the OSC message is being received and the group is being triggered, but the shock isn't actually delivered. I can sign into my partner's account on my machine to resolve this, but then the chat messages don't attribute who triggered the shock; also, while I'm okay with sharing logins with my partner, I understand it's not a solution for everyone.

I know this is an unsupported configuration and a very old feature request. For now, it seems like reverting to the pre-modularization version of ShockOSC is the path forward, and that's okay. I just wanted to see if there were any interest in potentially picking this back up. I'd even potentially be willing to take a stab at it, although I'm a little rusty with C#.

**Comment by LucHeart** [comment]
Open a new issue for this, this issue was from a time where shockosc didnt even have a ui, that when that was possible.
